import "server-only"

import type { SupabaseClient } from "@supabase/supabase-js"

type CourseCertificateParams = {
  admin: SupabaseClient
  learnerId: string
  learnerName: string
  courseId: string
  courseTitle: string
  issuedAt?: string
}

function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)")
}

function buildCourseCertificatePdf({
  learnerName,
  courseTitle,
  issuedDate
}: {
  learnerName: string
  courseTitle: string
  issuedDate: string
}) {
  const lines = [
    "0.18 0.48 0.84 rg",
    "72 700 468 2 re f",
    "0.18 0.48 0.84 RG",
    "48 48 516 696 re S",
    "58 58 496 676 re S",
    "BT",
    "/F1 20 Tf",
    "0.18 0.48 0.84 rg",
    "170 742 Td",
    `(CLOUDLMS CERTIFICATE) Tj`,
    "ET",
    "BT",
    "/F2 34 Tf",
    "0.08 0.11 0.17 rg",
    "118 648 Td",
    `(Certificate of Completion) Tj`,
    "ET",
    "BT",
    "/F1 18 Tf",
    "0.36 0.43 0.52 rg",
    "230 590 Td",
    `(Awarded to) Tj`,
    "ET",
    "BT",
    "/F2 30 Tf",
    "0.08 0.11 0.17 rg",
    "120 534 Td",
    `(${escapePdfText(learnerName)}) Tj`,
    "ET",
    "BT",
    "/F1 18 Tf",
    "0.36 0.43 0.52 rg",
    "150 470 Td",
    `(for successfully completing) Tj`,
    "ET",
    "BT",
    "/F2 26 Tf",
    "0.08 0.11 0.17 rg",
    "120 418 Td",
    `(${escapePdfText(courseTitle)}) Tj`,
    "ET",
    "BT",
    "/F1 16 Tf",
    "0.36 0.43 0.52 rg",
    "215 330 Td",
    `(Issued ${escapePdfText(issuedDate)}) Tj`,
    "ET",
    "BT",
    "/F1 14 Tf",
    "0.48 0.55 0.64 rg",
    "240 110 Td",
    `(Generated by CloudLMS) Tj`,
    "ET"
  ].join("\n")

  const stream = `${lines}\n`
  const objects = [
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    "2 0 obj\n<< /Type /Pages /Count 1 /Kids [3 0 R] >>\nendobj\n",
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>\nendobj\n",
    "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
    "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n",
    `6 0 obj\n<< /Length ${stream.length} >>\nstream\n${stream}endstream\nendobj\n`
  ]

  let pdf = "%PDF-1.4\n"
  const offsets = [0]

  objects.forEach((object) => {
    offsets.push(pdf.length)
    pdf += object
  })

  const xrefOffset = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n`
  pdf += "0000000000 65535 f \n"
  offsets.slice(1).forEach((offset) => {
    pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`
  })
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`

  return Buffer.from(pdf, "binary")
}

export async function issueCourseCertificate({
  admin,
  learnerId,
  learnerName,
  courseId,
  courseTitle,
  issuedAt = new Date().toISOString()
}: CourseCertificateParams) {
  const storageKey = `${learnerId}/${courseId}.pdf`
  const pdf = buildCourseCertificatePdf({
    learnerName,
    courseTitle,
    issuedDate: new Intl.DateTimeFormat("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric"
    }).format(new Date(issuedAt))
  })

  const uploadResult = await admin.storage
    .from("certificates")
    .upload(storageKey, pdf, {
      contentType: "application/pdf",
      upsert: true
    })

  if (uploadResult.error) {
    return {
      issued: false,
      storageKey
    }
  }

  const certificateResult = await admin.from("certificates").upsert(
    {
      user_id: learnerId,
      course_id: courseId,
      certificate_url: storageKey,
      issued_at: issuedAt
    },
    { onConflict: "user_id,course_id" }
  )

  return {
    issued: !certificateResult.error,
    storageKey
  }
}
